//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/schema3}ghaResponse">
 *       &lt;sequence>
 *         &lt;element name="idOperation" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authResponse", namespace = "http://www.example.org/schema3", propOrder = {
    "idOperation",
    "login"
})
public class AuthResponse
    extends GhaResponse
{

    @XmlElement(namespace = "http://www.example.org/schema3")
    protected int idOperation;
    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected String login;

    /**
     * Gets the value of the idOperation property.
     * 
     */
    public int getIdOperation() {
        return idOperation;
    }

    /**
     * Sets the value of the idOperation property.
     * 
     */
    public void setIdOperation(int value) {
        this.idOperation = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

}
