//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bpuData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bpuData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="institutions" type="{http://www.example.org/schema3}institutions" maxOccurs="unbounded"/>
 *         &lt;element name="workingAreas" type="{http://www.example.org/schema3}comboBoxElement" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bpuData", namespace = "http://www.example.org/schema3", propOrder = {
    "institutions",
    "workingAreas"
})
public class BpuData {

    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected List<Institutions> institutions;
    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected List<ComboBoxElement> workingAreas;

    /**
     * Gets the value of the institutions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the institutions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstitutions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Institutions }
     * 
     * 
     */
    public List<Institutions> getInstitutions() {
        if (institutions == null) {
            institutions = new ArrayList<Institutions>();
        }
        return this.institutions;
    }

    /**
     * Gets the value of the workingAreas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workingAreas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkingAreas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComboBoxElement }
     * 
     * 
     */
    public List<ComboBoxElement> getWorkingAreas() {
        if (workingAreas == null) {
            workingAreas = new ArrayList<ComboBoxElement>();
        }
        return this.workingAreas;
    }

}
