//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bpuPack complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bpuPack">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/schema3}infoPackData">
 *       &lt;sequence>
 *         &lt;element name="bpuPrimaryWaIo" type="{http://www.example.org/schema3}comboBoxElement"/>
 *         &lt;element name="bpuHoraryRestricted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bpuWaRestricted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bpuPkiRequired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="initialActionOnLogon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="initialForm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bpuPack", propOrder = {
    "bpuPrimaryWaIo",
    "bpuHoraryRestricted",
    "bpuWaRestricted",
    "bpuPkiRequired",
    "initialActionOnLogon",
    "initialForm"
})
public class BpuPack
    extends InfoPackData
{

    @XmlElement(required = true)
    protected ComboBoxElement bpuPrimaryWaIo;
    protected boolean bpuHoraryRestricted;
    protected boolean bpuWaRestricted;
    @XmlElement(required = true)
    protected String bpuPkiRequired;
    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected String initialActionOnLogon;
    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected String initialForm;

    /**
     * Gets the value of the bpuPrimaryWaIo property.
     * 
     * @return
     *     possible object is
     *     {@link ComboBoxElement }
     *     
     */
    public ComboBoxElement getBpuPrimaryWaIo() {
        return bpuPrimaryWaIo;
    }

    /**
     * Sets the value of the bpuPrimaryWaIo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComboBoxElement }
     *     
     */
    public void setBpuPrimaryWaIo(ComboBoxElement value) {
        this.bpuPrimaryWaIo = value;
    }

    /**
     * Gets the value of the bpuHoraryRestricted property.
     * 
     */
    public boolean isBpuHoraryRestricted() {
        return bpuHoraryRestricted;
    }

    /**
     * Sets the value of the bpuHoraryRestricted property.
     * 
     */
    public void setBpuHoraryRestricted(boolean value) {
        this.bpuHoraryRestricted = value;
    }

    /**
     * Gets the value of the bpuWaRestricted property.
     * 
     */
    public boolean isBpuWaRestricted() {
        return bpuWaRestricted;
    }

    /**
     * Sets the value of the bpuWaRestricted property.
     * 
     */
    public void setBpuWaRestricted(boolean value) {
        this.bpuWaRestricted = value;
    }

    /**
     * Gets the value of the bpuPkiRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBpuPkiRequired() {
        return bpuPkiRequired;
    }

    /**
     * Sets the value of the bpuPkiRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBpuPkiRequired(String value) {
        this.bpuPkiRequired = value;
    }

    /**
     * Gets the value of the initialActionOnLogon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialActionOnLogon() {
        return initialActionOnLogon;
    }

    /**
     * Sets the value of the initialActionOnLogon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialActionOnLogon(String value) {
        this.initialActionOnLogon = value;
    }

    /**
     * Gets the value of the initialForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialForm() {
        return initialForm;
    }

    /**
     * Sets the value of the initialForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialForm(String value) {
        this.initialForm = value;
    }

}
