//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataGlobalResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataGlobalResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/schema3}ghaResponse">
 *       &lt;sequence>
 *         &lt;element name="infoPacks" type="{http://www.example.org/schema3}dataGlobalInfoPacks"/>
 *         &lt;element name="parameters" type="{http://www.example.org/schema3}dataGlobalParameters"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataGlobalResponse", namespace = "http://www.example.org/schema3", propOrder = {
    "infoPacks",
    "parameters"
})
public class DataGlobalResponse
    extends GhaResponse
{

    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected DataGlobalInfoPacks infoPacks;
    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected DataGlobalParameters parameters;

    /**
     * Gets the value of the infoPacks property.
     * 
     * @return
     *     possible object is
     *     {@link DataGlobalInfoPacks }
     *     
     */
    public DataGlobalInfoPacks getInfoPacks() {
        return infoPacks;
    }

    /**
     * Sets the value of the infoPacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataGlobalInfoPacks }
     *     
     */
    public void setInfoPacks(DataGlobalInfoPacks value) {
        this.infoPacks = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link DataGlobalParameters }
     *     
     */
    public DataGlobalParameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataGlobalParameters }
     *     
     */
    public void setParameters(DataGlobalParameters value) {
        this.parameters = value;
    }

}
