//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataGlobalRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataGlobalRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="institutionId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="workingAreaId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataGlobalRequest", namespace = "http://www.example.org/schema3", propOrder = {
    "institutionId",
    "workingAreaId"
})
public class DataGlobalRequest {

    @XmlElement(namespace = "http://www.example.org/schema3")
    protected int institutionId;
    @XmlElement(namespace = "http://www.example.org/schema3")
    protected int workingAreaId;

    /**
     * Gets the value of the institutionId property.
     * 
     */
    public int getInstitutionId() {
        return institutionId;
    }

    /**
     * Sets the value of the institutionId property.
     * 
     */
    public void setInstitutionId(int value) {
        this.institutionId = value;
    }

    /**
     * Gets the value of the workingAreaId property.
     * 
     */
    public int getWorkingAreaId() {
        return workingAreaId;
    }

    /**
     * Sets the value of the workingAreaId property.
     * 
     */
    public void setWorkingAreaId(int value) {
        this.workingAreaId = value;
    }

}
