//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logonLogRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logonLogRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="instOrigen" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="instDest" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logonLogRequest", namespace = "http://www.example.org/schema3", propOrder = {
    "password",
    "login",
    "instOrigen",
    "instDest"
})
public class LogonLogRequest {

    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected String password;
    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected String login;
    @XmlElement(namespace = "http://www.example.org/schema3")
    protected int instOrigen;
    @XmlElement(namespace = "http://www.example.org/schema3")
    protected int instDest;

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the instOrigen property.
     * 
     */
    public int getInstOrigen() {
        return instOrigen;
    }

    /**
     * Sets the value of the instOrigen property.
     * 
     */
    public void setInstOrigen(int value) {
        this.instOrigen = value;
    }

    /**
     * Gets the value of the instDest property.
     * 
     */
    public int getInstDest() {
        return instDest;
    }

    /**
     * Sets the value of the instDest property.
     * 
     */
    public void setInstDest(int value) {
        this.instDest = value;
    }

}
