//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hocs.gha.frontend.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LogonLogRequest_QNAME = new QName("http://www.example.org/schema3", "logonLogRequest");
    private final static QName _ParameterResponse_QNAME = new QName("http://www.example.org/schema3", "parameterResponse");
    private final static QName _CodeRequest_QNAME = new QName("http://www.example.org/schema3", "codeRequest");
    private final static QName _FormCompsResponse_QNAME = new QName("http://www.example.org/schema3", "formCompsResponse");
    private final static QName _LogonLogResponse_QNAME = new QName("http://www.example.org/schema3", "logonLogResponse");
    private final static QName _CatalogResponse_QNAME = new QName("http://www.example.org/schema3", "catalogResponse");
    private final static QName _LoginResponse_QNAME = new QName("http://www.example.org/schema3", "loginResponse");
    private final static QName _LocationsResponse_QNAME = new QName("http://www.example.org/schema3", "locationsResponse");
    private final static QName _SingleSingOnUserResponse_QNAME = new QName("http://www.example.org/schema3", "singleSingOnUserResponse");
    private final static QName _InfoPackResponse_QNAME = new QName("http://www.example.org/schema3", "infoPackResponse");
    private final static QName _FormCompsRequest_QNAME = new QName("http://www.example.org/schema3", "formCompsRequest");
    private final static QName _DataGlobalRequest_QNAME = new QName("http://www.example.org/schema3", "dataGlobalRequest");
    private final static QName _SmnResponse_QNAME = new QName("http://www.example.org/schema3", "smnResponse");
    private final static QName _LoginRequest_QNAME = new QName("http://www.example.org/schema3", "loginRequest");
    private final static QName _DataGlobalResponse_QNAME = new QName("http://www.example.org/schema3", "dataGlobalResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hocs.gha.frontend.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FormResponse }
     * 
     */
    public FormResponse createFormResponse() {
        return new FormResponse();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link LogonLogResponse }
     * 
     */
    public LogonLogResponse createLogonLogResponse() {
        return new LogonLogResponse();
    }

    /**
     * Create an instance of {@link CatalogResponse }
     * 
     */
    public CatalogResponse createCatalogResponse() {
        return new CatalogResponse();
    }

    /**
     * Create an instance of {@link LogonLogRequest }
     * 
     */
    public LogonLogRequest createLogonLogRequest() {
        return new LogonLogRequest();
    }

    /**
     * Create an instance of {@link CodeRequest }
     * 
     */
    public CodeRequest createCodeRequest() {
        return new CodeRequest();
    }

    /**
     * Create an instance of {@link ParameterResponse }
     * 
     */
    public ParameterResponse createParameterResponse() {
        return new ParameterResponse();
    }

    /**
     * Create an instance of {@link DataGlobalResponse }
     * 
     */
    public DataGlobalResponse createDataGlobalResponse() {
        return new DataGlobalResponse();
    }

    /**
     * Create an instance of {@link InfoPackResponse }
     * 
     */
    public InfoPackResponse createInfoPackResponse() {
        return new InfoPackResponse();
    }

    /**
     * Create an instance of {@link DataGlobalRequest }
     * 
     */
    public DataGlobalRequest createDataGlobalRequest() {
        return new DataGlobalRequest();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link SingleSingOnUserResponse }
     * 
     */
    public SingleSingOnUserResponse createSingleSingOnUserResponse() {
        return new SingleSingOnUserResponse();
    }

    /**
     * Create an instance of {@link LocationsResponse }
     * 
     */
    public LocationsResponse createLocationsResponse() {
        return new LocationsResponse();
    }

    /**
     * Create an instance of {@link BpuPack }
     * 
     */
    public BpuPack createBpuPack() {
        return new BpuPack();
    }

    /**
     * Create an instance of {@link DataGlobalInfoPacks }
     * 
     */
    public DataGlobalInfoPacks createDataGlobalInfoPacks() {
        return new DataGlobalInfoPacks();
    }

    /**
     * Create an instance of {@link ErrorInfo }
     * 
     */
    public ErrorInfo createErrorInfo() {
        return new ErrorInfo();
    }

    /**
     * Create an instance of {@link Institutions }
     * 
     */
    public Institutions createInstitutions() {
        return new Institutions();
    }

    /**
     * Create an instance of {@link GhaResponse }
     * 
     */
    public GhaResponse createGhaResponse() {
        return new GhaResponse();
    }

    /**
     * Create an instance of {@link SmnMessage }
     * 
     */
    public SmnMessage createSmnMessage() {
        return new SmnMessage();
    }

    /**
     * Create an instance of {@link DataGlobalParameters }
     * 
     */
    public DataGlobalParameters createDataGlobalParameters() {
        return new DataGlobalParameters();
    }

    /**
     * Create an instance of {@link SmnResponse }
     * 
     */
    public SmnResponse createSmnResponse() {
        return new SmnResponse();
    }

    /**
     * Create an instance of {@link InfoPack }
     * 
     */
    public InfoPack createInfoPack() {
        return new InfoPack();
    }

    /**
     * Create an instance of {@link SmnNotification }
     * 
     */
    public SmnNotification createSmnNotification() {
        return new SmnNotification();
    }

    /**
     * Create an instance of {@link MessageParameter }
     * 
     */
    public MessageParameter createMessageParameter() {
        return new MessageParameter();
    }

    /**
     * Create an instance of {@link OperationParameter }
     * 
     */
    public OperationParameter createOperationParameter() {
        return new OperationParameter();
    }

    /**
     * Create an instance of {@link BpiParameter }
     * 
     */
    public BpiParameter createBpiParameter() {
        return new BpiParameter();
    }

    /**
     * Create an instance of {@link BpuData }
     * 
     */
    public BpuData createBpuData() {
        return new BpuData();
    }

    /**
     * Create an instance of {@link BpiPackData }
     * 
     */
    public BpiPackData createBpiPackData() {
        return new BpiPackData();
    }

    /**
     * Create an instance of {@link AuthResponse }
     * 
     */
    public AuthResponse createAuthResponse() {
        return new AuthResponse();
    }

    /**
     * Create an instance of {@link BpuAccessPack }
     * 
     */
    public BpuAccessPack createBpuAccessPack() {
        return new BpuAccessPack();
    }

    /**
     * Create an instance of {@link SmnAlarm }
     * 
     */
    public SmnAlarm createSmnAlarm() {
        return new SmnAlarm();
    }

    /**
     * Create an instance of {@link ComboBoxElement }
     * 
     */
    public ComboBoxElement createComboBoxElement() {
        return new ComboBoxElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogonLogRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "logonLogRequest")
    public JAXBElement<LogonLogRequest> createLogonLogRequest(LogonLogRequest value) {
        return new JAXBElement<LogonLogRequest>(_LogonLogRequest_QNAME, LogonLogRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "parameterResponse")
    public JAXBElement<ParameterResponse> createParameterResponse(ParameterResponse value) {
        return new JAXBElement<ParameterResponse>(_ParameterResponse_QNAME, ParameterResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "codeRequest")
    public JAXBElement<CodeRequest> createCodeRequest(CodeRequest value) {
        return new JAXBElement<CodeRequest>(_CodeRequest_QNAME, CodeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "formCompsResponse")
    public JAXBElement<FormResponse> createFormCompsResponse(FormResponse value) {
        return new JAXBElement<FormResponse>(_FormCompsResponse_QNAME, FormResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogonLogResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "logonLogResponse")
    public JAXBElement<LogonLogResponse> createLogonLogResponse(LogonLogResponse value) {
        return new JAXBElement<LogonLogResponse>(_LogonLogResponse_QNAME, LogonLogResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatalogResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "catalogResponse")
    public JAXBElement<CatalogResponse> createCatalogResponse(CatalogResponse value) {
        return new JAXBElement<CatalogResponse>(_CatalogResponse_QNAME, CatalogResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "loginResponse")
    public JAXBElement<LoginResponse> createLoginResponse(LoginResponse value) {
        return new JAXBElement<LoginResponse>(_LoginResponse_QNAME, LoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "locationsResponse")
    public JAXBElement<LocationsResponse> createLocationsResponse(LocationsResponse value) {
        return new JAXBElement<LocationsResponse>(_LocationsResponse_QNAME, LocationsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SingleSingOnUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "singleSingOnUserResponse")
    public JAXBElement<SingleSingOnUserResponse> createSingleSingOnUserResponse(SingleSingOnUserResponse value) {
        return new JAXBElement<SingleSingOnUserResponse>(_SingleSingOnUserResponse_QNAME, SingleSingOnUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoPackResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "infoPackResponse")
    public JAXBElement<InfoPackResponse> createInfoPackResponse(InfoPackResponse value) {
        return new JAXBElement<InfoPackResponse>(_InfoPackResponse_QNAME, InfoPackResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "formCompsRequest")
    public JAXBElement<String> createFormCompsRequest(String value) {
        return new JAXBElement<String>(_FormCompsRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataGlobalRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "dataGlobalRequest")
    public JAXBElement<DataGlobalRequest> createDataGlobalRequest(DataGlobalRequest value) {
        return new JAXBElement<DataGlobalRequest>(_DataGlobalRequest_QNAME, DataGlobalRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "smnResponse")
    public JAXBElement<String> createSmnResponse(String value) {
        return new JAXBElement<String>(_SmnResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "loginRequest")
    public JAXBElement<LoginRequest> createLoginRequest(LoginRequest value) {
        return new JAXBElement<LoginRequest>(_LoginRequest_QNAME, LoginRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataGlobalResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/schema3", name = "dataGlobalResponse")
    public JAXBElement<DataGlobalResponse> createDataGlobalResponse(DataGlobalResponse value) {
        return new JAXBElement<DataGlobalResponse>(_DataGlobalResponse_QNAME, DataGlobalResponse.class, null, value);
    }

}
