//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameterResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameterResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/schema3}ghaResponse">
 *       &lt;sequence>
 *         &lt;element name="parameter" type="{http://www.example.org/schema3}ghaParameter"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameterResponse", namespace = "http://www.example.org/schema3", propOrder = {
    "parameter"
})
public class ParameterResponse
    extends GhaResponse
{

    @XmlElement(namespace = "http://www.example.org/schema3", required = true)
    protected GhaParameter parameter;

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link GhaParameter }
     *     
     */
    public GhaParameter getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link GhaParameter }
     *     
     */
    public void setParameter(GhaParameter value) {
        this.parameter = value;
    }

}
