//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for smnResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="smnResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/schema3}ghaResponse">
 *       &lt;sequence>
 *         &lt;element name="alarms" type="{http://www.example.org/schema3}smnAlarm" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="messages" type="{http://www.example.org/schema3}smnMessage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="notifications" type="{http://www.example.org/schema3}smnNotification" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "smnResponse", namespace = "http://www.example.org/schema3", propOrder = {
    "alarms",
    "messages",
    "notifications"
})
public class SmnResponse
    extends GhaResponse
{

    @XmlElement(namespace = "http://www.example.org/schema3")
    protected List<SmnAlarm> alarms;
    @XmlElement(namespace = "http://www.example.org/schema3")
    protected List<SmnMessage> messages;
    @XmlElement(namespace = "http://www.example.org/schema3")
    protected List<SmnNotification> notifications;

    /**
     * Gets the value of the alarms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alarms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlarms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmnAlarm }
     * 
     * 
     */
    public List<SmnAlarm> getAlarms() {
        if (alarms == null) {
            alarms = new ArrayList<SmnAlarm>();
        }
        return this.alarms;
    }

    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmnMessage }
     * 
     * 
     */
    public List<SmnMessage> getMessages() {
        if (messages == null) {
            messages = new ArrayList<SmnMessage>();
        }
        return this.messages;
    }

    /**
     * Gets the value of the notifications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notifications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotifications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmnNotification }
     * 
     * 
     */
    public List<SmnNotification> getNotifications() {
        if (notifications == null) {
            notifications = new ArrayList<SmnNotification>();
        }
        return this.notifications;
    }

}
