/*
 * Copyright (c) 2014. Colocar el texto de propiedad
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.05 at 05:22:28 PM UTC 
//


package com.hocs.gha.frontend.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testRequest", namespace = "http://www.example.org/schema3", propOrder = {
        "componentId",
        "data",
        "dataSource",
        "oldValues",
        "operationType",
        "textMatchStyle"
})
public class TestRequest {

    @XmlElement()
    protected String componentId;
    protected Object data;
    protected int startRow;
    protected int endRow;
    protected Object oldValues;
    protected String dataSource;
    protected String operationType;
    protected String textMatchStyle;
    protected int sessionId; // id de la sesion del usaurio
    protected String token; // el  token identificador del usuario


    public String getDataSource() {
        return dataSource;
    }

    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    public String getOperationType() {
        return operationType;
    }

    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    public String getTextMatchStyle() {
        return textMatchStyle;
    }

    public void setTextMatchStyle(String textMatchStyle) {
        this.textMatchStyle = textMatchStyle;
    }

    public Object getData() {
        return data;
    }

    public void setData(Object data) {
        this.data = data;
    }

    public Object getOldValues() {
        return oldValues;
    }

    public void setOldValues(Object oldValues) {
        this.oldValues = oldValues;
    }

    public String getComponentId() {
        return componentId;
    }

    public void setComponentId(String componentId) {
        this.componentId = componentId;
    }

    public int getStartRow() {
        return startRow;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public int getEndRow() {
        return endRow;
    }

    public void setEndRow(int endRow) {
        this.endRow = endRow;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}

